sonar.projectKey=ChatStream
sonar.projectName=ChatStream
sonar.projectVersion=1.0

sonar.sources=package

sonar.host.url=http://localhost:9000
sonar.token=sqp_93698840939c04f347eced848fc5725be30c7ad8




sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/examples/**,**/release/**,**/*.java,**/*.kt
